### ISSUE TITLE
Investments not refreshed on account update

### ISSUE THREAD

**Issue by argaen** [maffin-io/maffin-app#605]
When updating an account type from 'ASSET' to 'INVESTMENT' or vice-versa, the investment page still reflects the old data. This is because the data is cached under the `/api/investments` key.

In order to update the cached key, we need to `mutate` it in the `AccountForm`. See https://github.com/maffin-io/maffin-app/blob/master/src/components/forms/account/AccountForm.tsx#L325

I guess ideally, would be good if the account before was of type 'INVESTMENT' or the new type being set is 'INVESTMENT' so we only re-calculate the key when this specific thing happens, but happy to be pragmatic and update always and see what happens.

PS: Don't remember to update tests in `AccountForm.test.tsx` to make sure this new key is cleared when we update!

**Comment by corinetiah** [comment]
I give up
