### ISSUE TITLE
Liabilities dashboard is not intuitive

### ISSUE THREAD

**Issue by corinetiah** [maffin-io/maffin-app#834]
The logic is correct for liabilities, however, the dahsboard displayed makes one think that my liability amount is going up, even when I am making repayments. 

Changing to absolute numbers would be more user-friendly to tick the right boxes in a user's brain.
![Screenshot 2024-04-07 at 7 24 57 PM](https://github.com/maffin-io/maffin-app/assets/124553339/08d84369-6008-4937-82d9-b60f45adaff6)

**Comment by argaen** [comment]
Okay things I think will do here:

- change the numbers in the "net worth" graph to be absolute
- change the title to be "Owed" or smth like this
- Try to align the widgets so they have the same weight
