### ISSUE TITLE
Rewrite docs on account creation restrictions

### ISSUE THREAD

**Issue by corinetiah** [maffin-io/maffin-app#842]
Either a new section here: https://maffin.notion.site/Tracking-Investments-0ae2031366874853889e19edfe008ce7

or a new standalone FAQ page: 
<img width="429" alt="Screenshot 2024-04-08 at 9 17 53 PM" src="https://github.com/maffin-io/maffin-app/assets/124553339/66850227-212c-4223-93e4-59aed914f907">

Maybe the latter so it doesn't overwhelm the TSLA example

**Comment by argaen** [comment]
Closing this for now as the restrictions were improved in https://github.com/maffin-io/maffin-app/pull/844
